name: CI

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build & pack
        run: |
          dotnet tool restore
          dotnet cake --target=pack
        working-directory: ./tools/cake/
