name: release

on:
  push:
    tags: 
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "true"

      - name: build & pack
        run: |
          dotnet tool restore
          dotnet cake --target=pack
        working-directory: ./tools/cake/

      - name: nuget push
        if: startsWith(github.ref, 'refs/tags/')  
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: |
          dotnet cake --target=push
        working-directory: ./tools/cake/

      - uses: "marvinpinto/action-automatic-releases@latest"
        if: startsWith(github.ref, 'refs/tags/')
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            ./src/d3/*.nupkg